ministryofjustice/create-and-vary-a-licence-api

- helm_deploy/create-and-vary-a-licence-api/values.yaml
Corrected database_user to database_username within the rds-instance-output secret.
> CVL-14: Corrected RDS secret name

- Dockerfile
- build.gradle.kts
Minor changes:
* Dockerfile - added an upgrade step to get latest libssl (and other) changes.
* Gradle dependencies - minor updates to get latest versions
* New way to set the java 16 language on gradle tasks.
> CVSL-96: Updated dependencies and Dockerfile change to pull latest libssl to fix overnight build.

- README.md
- build.gradle.kts
- From MoJ Springboot library 3.3.8 release notes
```
CVE-2020-0822 states: | An elevation of privilege vulnerability exists when the Windows Language Pack Installer improperly handles file operations, aka 'Windows Language Pack Installer Elevation of Privilege Vulnerability'.
This does not affect linux distributions so needs to be suppressed.
```
> CVSL-113: Upgrade MoJ Springboot Library to resolve security vulnerability CVE-2020-0822

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/LicenceController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/TestController.kt
This PR fixes:
* Swagger was not showing the 200 response + `CreateLicenceResponse` type/example.
* Swagger was not showing the 4xx response + `ErrorResponse` type / example.
> CVSL-126: Correct the swagger documentation for response types.

- build.gradle.kts
Update to plugin 3.3.9 to suppress vulnerabilities being reported by trivy.
> CVSL-130: Update gradle plugin to suppress current vulnerabilities

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/entity/AdditionalCondition.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/entity/AdditionalConditionData.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/entity/Licence.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/AdditionalCondition.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/AdditionalConditionsRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/LicenceController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/TransformFunctions.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/LicenceIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/LicenceControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceServiceTest.kt
- Refactored the ManyToOne mapping for additional conditions to make use of Hibernates ability to manage the referential integrity for us. Should probably do this for bespoke and standard conditions too...
- Left the additional data endpoint for now.. needs some more thinking about
> CVSL-106: Update the list of additional conditions

- src/main/resources/migration/common/V11__create_licence_tables.sql
- No restriction to the allowed length of the data field
- Requires database to be dropped to take effect
> CVSL-184: Lengthen data field for additional conditions

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/LicenceController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/LicenceIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceServiceTest.kt
New endpoint `/licence/activate-licences` which accepts a list of licence IDs, and changes the status of each of those licences to ACTIVE
> CVSL-174: Add endpoint to activate licences in bulk

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/CreateLicenceRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/LicenceSummary.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/SubmitLicenceRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/repository/LicenceRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/LicenceController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/TransformFunctions.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/LicenceIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/LicenceControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceServiceTest.kt
- Also removed the `getLicencesByStaffIdAndStatuses` endpoint as it's no longer used
> CVSL-274: Add submit licence endpoint which saves the COMs details

- build.gradle.kts
To fix overnight security scan jobs.
> CVSL-286: Update gradle plugin and move H2 to test dependency only

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/ExclusionZoneService.kt
Extracting the full-size image from the PDF produces a better/bigger image, but loses the zone overlay shape - which is kind of the point of the map! This change reverts to rendering page-1 of the PDF as an image, but then cropping away the borders so that we produce a reasonable map + overlay zone.
> CVSL-313: Revert to page render for map. Crop the borders away.

- README.md
- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/kotlinjpaspecificationdsl/JPASpecificationDSL.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/repository/LicenceSpecifications.kt
This is no longer available from the JCenter repo now.
Imported the single file (Apache 2.0) licence conditions.
> CVSL-339: Import kotlin JPA specification directly

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/entity/AuditEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/AuditEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/AuditRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/repository/AuditEventRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/AuditController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/AuditService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/OffenderService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/TransformFunctions.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/util/AuditEventType.kt
- src/main/resources/migration/common/V16__create_audit_event.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/AuditIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/AuditControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/AuditServiceTest.kt
- src/test/resources/test_data/clear-audit-events.sql
- src/test/resources/test_data/seed-audit-events.sql
*  Audited events can be related to a user, a licence, or both.
* They may not be in relation to a change to data - e.g. could be for when a user views a licence.
* They may not be related to a licence - so no referential integrity to licence data.
* Endpoints to create an audit event, get events for a user, get events for a licence, and get all events
* Events are queried between two dates (defaulted to 1 month if not supplied).
> CVSL-361 add auditing features

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/repository/LicenceSpecifications.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/LicenceMatchingIntegrationTest.kt
- src/test/resources/test_data/seed-community-offender-manager.sql
- src/test/resources/test_data/seed-matching-candidates.sql
* Re-instates the commented-out tests for matching on staffIds
* Makes the JPA Specification methods look down into the joined tables for staff.
* Adds test data to filtering by various criteria
> CVSL-402: Update JPA specification methods for joined COM table

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/entity/BespokeCondition.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/entity/Licence.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/entity/StandardCondition.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/Licence.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/request/UpdateReasonForVariationRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/request/UpdateSpoDiscussionRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/request/UpdateVloDiscussionRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/LicenceController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/TransformFunctions.kt
- src/main/resources/migration/common/V11__create_licence_tables.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/LicenceIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/LicenceControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/ExclusionZoneServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceServiceTest.kt
- 5 new endpoints:
- create variation
- discard
- update spo discussion
- update vlo discussion
- update reason for variation
- Requires DB re-create
> CVSL-390: Add new endpoints for licence variation, and an endpoint for discarding licences

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/entity/CommunityOffenderManager.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/UpdateComRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/ComService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceService.kt
- src/main/resources/migration/common/V10__create_com_details_table.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/LicenceIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/OffenderIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/OffenderControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/ComServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/OffenderServiceTest.kt
- src/test/resources/test_data/clear-all-data.sql
- src/test/resources/test_data/seed-community-offender-manager.sql
PLEASE DO NOT MERGE - requires sequencing with UI changes & a DB drop/recreate
Caters for auditing change events within the API for:
* Create a licence
* Submit a licence
* Approve or reject a licence
* Edit a licence
* Set to Recall or Inactive
* Variation created
* Variated submitted
* Adds first_name, last_name into COM details table
> CVSL-386: Refactoring audit to be within the API for change events

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/repository/BespokeConditionRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceServiceTest.kt
Because the bespoke conditions are now joined by hibernate, instead of a manual join by id, the deletion by ID no longer works. Instead, the entity should be updated with an empty list
Infact, the BespokeConditionRepository should not exist, and should be handled through the licence repository as a join, but this is a bigger piece of work to refactor
> Fix deletion of bespoke conditions

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
Attempt to fix broken deployment - indicates container[0] - the API, and env var [3] - this one.
> CVSL-432: Remove unused env var now supplied by secrets

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/NotifyService.kt
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/NotifyIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/NotifyServiceTest.kt
Configures environment-specific email links for notifications.
The Gov Uk Notify templates have been updated to include the links for the following emails:
* Initial prompt to create a licence (12-week)
* Reminder to create a licence (4-week)
* PDU head licence notification of a licence awaiting approval
> CVSL-450: Embedded self-referencing (env-specific) links into the email notifications

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/Licence.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/TransformFunctions.kt
- src/main/resources/migration/common/V19__create_extra_licence_index.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceServiceTest.kt
3 minor changes:
* When a licence variation is approved by the ACO the status is changed to VARIATION_APPROVED instead of ACTIVE.
* I've added an index to the licence column `variation_of_id` so that we can quickly find discarded variations later.
* Added a new field `createdByFullName` into the licence model object, and populated this from the createdBy join column.
> CVSL-457 Variation approval status

- build.gradle.kts
v4.1.2 -> v4.1.3 to update spring boot and fix overnight vulnerabilities reported.
> CVSL-497: Update gradle plugin to fix vulnerabilities

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceService.kt
Small change - if no user present, or user.username == 'SYSTEM' then select the SYSTEM_EVENT for audit, otherwise USER_EVENT.
> CVSL-464: Choosing SYSTEM or USER event more correctly in auditing

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/repository/CommunityOffenderManagerRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/ComService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/ComServiceTest.kt
When updating a COM, check for a match against username or staffId. Its possible the staffId can be changed in nDelius to link to another account. If this instance, we should update the existing record in CVL to reflect the new username and or staffId.
Failing to do so will result in a key constraint failure; causing a crash.
Check the COM details have changed before performing any update.
> Cvsl 596 com update id changes

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/entity/OmuContact.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/request/UpdateOmuEmailRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/repository/OmuContactRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/OmuContactController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/OmuService.kt
- src/main/resources/migration/common/V21__store_omu_contact.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/OmuContactIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/OmuContactControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/OmuServiceTest.kt
- src/test/resources/test_data/clear-all-data.sql
- src/test/resources/test_data/seed-omu-contact-data.sql
Add a new OMU Contact service, initially providing CRUD functionality for OMU email addresses. The service can later be expanded to hold more OMU details if required.
> Cvsl 526 omu contact service

- README.md
- helm_deploy/create-and-vary-a-licence-api/values.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/config/WebClientConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceFunctions.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/prison/PrisonApiClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/prison/PrisonerHdcStatus.kt
- src/main/resources/application-dev.yml
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/LicenceIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/wiremock/PrisonApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceServiceTest.kt
- src/test/resources/application-test.yml
Add oauth client configuration along with PrisonAPI WebClient Bean. Check HDC status is not Approved before emailing sentence changes in regard to a Standard Licence. Update deployment variables with the existing system client and secret used by CVL Node application.
> Cvsl 618 check hdc status

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/config/PolicyConfiguration.kt
change jackson argument to input stream in order to prevent file path issues when accessing resource from the Jar file
> change jackson argument to input stream

- src/main/resources/policy_conditions/policyV2.1.json
Preventing use of shared condition type definition, as the validations needed to diverge between the new and old versions
> CVSL-138 Replacing old condition type with new one

- src/main/resources/policy_conditions/policyV1.json
Validations are currently broken on v1.0 licences as the types are missing from the policy doc.
This also causes any conditions with address fields to be unsubmittable because the lack of a `stringify` method it causes a 400 error (introduced by the validator) means the address submits in a format that the API cannot handle.
> Adding additional conditions type to v1.0 policy to fix broken validations

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/repository/LicenceSpecifications.kt
Before the change, "Get licences matches - no filters" test used to generate the following queries:
```
Hibernate: select ... from licence licence0_
Hibernate: select ... from community_offender_manager communityo0_ where communityo0_.id=? Hibernate: select ... from community_offender_manager communityo0_ where communityo0_.id=? Hibernate: select ... from community_offender_manager communityo0_ where communityo0_.id=? ...
```
After this change it generates:
```
select ... from licence licence0_ inner join community_offender_manager communityo1_ on licence0_.responsible_com_id=communityo1_.id
```
Combined with another bug this would generate up to an extra 25-30k sql queries per minute
> CVSL-750 fixing N+1 issue

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/repository/CommunityOffenderManagerRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/ComService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/OffenderIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/ComServiceTest.kt
It appears that duplicate COM accounts were being created due to a combination of a few factors:
- HMPPS auth returns a normalised version of the username, in uppercase, whereas Delius returns the username as it exists (often lowercase)
- When a COM gets given a new account (possible due to moving probation region), they keep the same username but get a new Staff Indentifier
- Our existing COM record lookup is case sensitive
These three issues combine into a situation where it's possible for two accounts with the same username in different cases to be presumed by CVL to be two unique users, as they have different staff IDs and different casing of username. This then later causes an error when a subsequent search finds both COM records connected to one (differently-cased) username.
This …
> CVSL-758 - Forcing COM usernames to be uppercase and removing case sensitivity on lookup

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/probation/CommunityApiClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/probation/Team.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/probation/User.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/ComIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/wiremock/CommunityApiMockServer.kt
- src/test/resources/application-test.yml
This PR is to add an endpoint call to the community api to retrieve the team codes for a user based on their staff identifier.
> CVSL-1030 Add call to community api endpoint to get team codes for a user

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/entity/CommunityOffenderManager.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/entity/Licence.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/LicenceConditionIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/LicenceMatchingIntegrationTest.kt
- src/test/resources/test_data/seed-a-few-licences.sql
- src/test/resources/test_data/seed-community-offender-manager.sql
Depending on the way the criteria object was created it could trigger up to 4*n+1 queries as it would eagerly load the various collections of conditions and com details. This was all unnecessary as the matches endpoint produces LicenceSummarys which do not surface any info about additional conditions and only provide info about the responsible com
There still seems to be an n+1 query as it seems to retrieve the created com even though its not being used - still not really sure why!
None of the other methods retrieving multiple Licences require access to associated entities (conditions/other coms). If we need to add these methods we should add custom methods that have appropriate fetch strategies. Using the generic "match" endpoint would be inappropriate for that
> CSVSL-1048 Improving performance by reducing the number of n+1 issues

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/policy/AdditionalConditionAp.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/policy/AdditionalConditionPss.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/policy/Conditional.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/policy/ConditionalInput.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/policy/Input.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/policy/LicencePolicy.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/ConditionFormatter.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/FormattingHelpers.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/PolicyFunctions.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/policies/PolicyV1.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/policies/PolicyV2.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/policies/PolicyV2Dot1.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/ConditionFormatterTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/FormattingHelpersTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/PolicyFunctionsTest.kt
- src/test/resources/test_data/policy_conditions/policyV1.json
- src/test/resources/test_data/policy_conditions/policyV2.json
- src/test/resources/test_data/policy_conditions/policyV2_1.json
This also fixes a couple of bugs:
* Incorrect casing of some inputs due to typo - captilise vs capitalised
* Incorrectly capitalise the joining word: or vs Or
This still needs to be hooked up, may dual run for a bit to identify any issues but then hope to remove the code from the frontend and move to stop exposing formatting rules
> CVSL-1127 Adding condition formatter to the backend

- README.md
- docker-compose.yml
- run-local.sh
This PR takes the previous work around API automation one step further and creates a one stop script to build front and back end containers and run the back end from the API. There is still one step of manual operation to run the frontend from the root of the UI repo.
> FB Automate Building API Extension

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/AdditionalConditionRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/AdditionalConditionsRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/ToEntityTransformers.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/LicenceConditionIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/LicenceControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceConditionServiceTest.kt
This removes these fields:
```
val id: Long? = -1,
val text: String? = null,
val expandedText: String? = null,
val data: List<AdditionalConditionData> = emptyList(),
val uploadSummary: List<AdditionalConditionUploadSummary> = emptyList(),
```
this should be backwards compatible as jackson will ignore unknown fields (and they weren't being used anyway)
> CVSL-1127 Move to lighter model for updating additional conditions

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/FoundProbationRecord.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/ToModelTransformers.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/ComIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/ComControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/ComServiceTest.kt
This PR is to add some additional fields for the search response from the API to enable the results table to be displayed accurately in the frontend.
> CVSL-999 add additional fields for search response

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/FoundProbationRecord.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/ToModelTransformers.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/ComIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/ComControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/ComServiceTest.kt
This PR is to include a field missed off the previous PR for staff code.
> CVSL-999 add missed field for search

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceService.kt
The only call to this endpoint currently comes from the licenceExpiryService, which deactivates active licences, so the limitation of only finding `APPROVED` licences needs to be removed.
> CVSL-1364 Removing filtering to APPROVED licences for licence deactivation endpoint

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/publicApi/PublicLicenceController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/publicApi/PublicLicenceService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/publicApi/ToModelTransformers.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/publicApi/PublicLicenceServiceIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/publicApi/PublicLicenceControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/publicApi/PublicLicenceServiceTest.kt
This PR is to add a new endpoint to the CVL public API to allow a list of licence summary representations to be returned based on prison number.
> CVSL-1278 create endpoint to get licences based on prison number

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceServiceTest.kt
By this time the code reaches the point of the added line, the only possibility is for the original licence to be APPROVED and the new edit to be IN_PROGRESS, therefore no additional checks are needed.
> CVSL-1425 Adding missing call to send reapproval email on licence edit

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/publicApi/PublicLicenceController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/publicApi/PublicLicenceService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/publicApi/PublicLicenceServiceIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/privateApi/BankHolidayControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/publicApi/PublicLicenceControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/publicApi/PublicLicenceServiceTest.kt
This PR is to add a new endpoint to the CVL public API to allow a JPEG image of an exclusion zone to be returned based on the ID of the condition that is required.
> CVSL-1280 add endpoint to get full size image for exclusion zone based on condition id

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/publicApi/PublicLicencePolicyController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/publicApi/PublicLicencePolicyService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/publicApi/PublicLicencePolicyServiceIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/publicApi/PublicLicencePolicyControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/publicApi/PublicLicencePolicyServiceTest.kt
This PR adds a new endpoint /policy/latest endpoint This new endpoint returns most recent version of policy. At the moment its going to return version 2.1. This PR assumes that there is at least one policy present always.
> add /policy/latest endpoint

- helm_deploy/create-and-vary-a-licence-api/Chart.yaml
- helm_deploy/create-and-vary-a-licence-api/values.yaml
This PR migrates the project to use groups of IPs in their allowlist.
By referring to groups to IP addresses, we can centralize the definition of groups of ip addresses.
If these lists require changing in the future, we can change the definition once and future deploys across all services will automatically include these new IPs.
1 allowlist(s) have been detected that can be migrated.
The effect of applying this PR is as follows:
- The following groups will be applied: `internal`
- The size of the allowlist defined in this file will change: `8 => 1 (7 removed)`
The new Group membership will result in the following IPs being added to your allowlist by applying this PR:
- petty-france-wifi
The following IPs have been identified as unnecessary and will be removed by applying this PR:
- …
> Migrating project to use groups in allowlist

- detekt-baseline.xml
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/ComService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/probation/ProbationSearchApiClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/probation/model/request/LicenceCaseloadSearchRequest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/ComIntegrationTest.kt
This PR is to add the page size to the initial licence caseload search call we make when using search. This is off the back of initial investigation around search results following the addition of the Eligibility Service. There are too few results being returned and this seems like the culprit.
> CVSL-1412 add page size to licence caseload call

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/ComService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/ToModelTransformers.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/probation/CaseloadResponse.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/probation/CaseloadResult.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/probation/ProbationSearchApiClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/probation/ProbationSearchResponse.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/ComServiceTest.kt
This PR is a simple one to rename some of the classes around the Probation Search API so they are indicative of what is being returned.
> Rename existing classes to match what is being returned

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/probation/OffenderDetail.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/probation/OffenderManager.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/probation/OtherIds.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/probation/ProbationSearchApiClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/probation/StaffDetail.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/probation/model/request/OffenderSearchRequest.kt
This PR is to add a `/search` call from the Probation Search API client as this is needed to move the licence creation to the backend.
> CVSL-1505 add probation search call to api client

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/prison/PrisonerSearchPrisoner.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/probation/CommunityOrPrisonOffenderManager.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/probation/Detail.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/probation/Manager.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/probation/OffenderDetail.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/probation/OtherIds.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/probation/ProbationAreaDetail.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/probation/TeamDetail.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/wiremock/PrisonerSearchMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/ComServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/EligibilityServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/IS91DeterminationServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/jobs/LicenceActivationServiceTest.kt
This latest PR introduces some extra variables we will need to expose from responses to various external API's in order to create the licence in the backend.
> CVSL-1505 add parameters needed to create licences in the backend

- .circleci/config.yml
- docker-compose.yml
- run-local.sh
- src/main/resources/application-dev.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/IntegrationTestBase.kt
- src/test/resources/application-test.yml
This PR is to add localstack to CVL which will enable us to create mock versions of AWS services such as queues and notifications within our integration tests and locally, making tests queues, a lot easier.
> CVSL-1516 add localstack

- docker-compose.yml
- src/main/resources/application-dev.yml
This PR adds some changes to the `docker-compose.yml` file to allow two Localstack instances to run at the same time. Once we move events to the backend and remove Localstack from the front end, we can revert these values back to the default values.
> CVSL-1516 add extra config to change port numbers for localstack locally

- build.gradle.kts
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/config/LocalStackContainer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/IntegrationTestBase.kt
This PR is to add a Testcontainers option when running integration tests so that if a LocalStack instance does not exist for testing, a Testcontainers instance of LocalStack is created.
> CVSL-1516 add testcontainers config

- helm_deploy/values-test1.yaml
- helm_deploy/values-test2.yaml
This PR is to address an issue where the topic arn was not visible in test1 and test2, as the `serviceAccountName` for those envs is different in CP to the other API namespaces.
> CVSL-1516 change serviceAccountName in test1 and test2

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/CaseloadService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/EligibilityService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/CaseloadServiceTest.kt
This PR follows testing of CVSL-1483 where we have found that just having two existing licence checks for an ARD/CRD in the future and an active prison status is problematic, when checking existing licences. Instead, for any person in prison with a non probation licence status :
- `IN_PROGRESS`
- `SUBMITTED`
- `APPROVED`
we will carry out a full eligibility check and will continue to do so while their licence is in any of the statuses above. If the person has a licence in the status above and fails eligibility, they will not be returned in the results as they are now ineligible to use CVL. We would only stop checking eligibility when their licence becomes `ACTIVE` or another probation licence status (`VARIATION_*`)
> CVSL-1483 change check to run all eligibility checks against a person in prison

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- helm_deploy/values-test1.yaml
- helm_deploy/values-test2.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/domainEvents/DomainEventsService.kt
- src/main/resources/application.yml
This PR is following feedback from the Delius integration team that the `detailUrl` is pointing to the frontend and not the API so this means the link is obsolete. Changed the link to ensure the public API licence URL points to the API and not the frontend.
> CVSL-1517 amend detail url

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/domainEvents/DomainEventsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/domainEvents/OutboundEventsPublisher.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/DeactivateLicencesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/LicenceActivationIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/LicenceIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/LicenceOverrideIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/domainEvents/DomainEventsServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/domainEvents/OutboundEventsPublisherTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/jobs/DeactivateLicencesServiceTest.kt
This PR is in response to the Delius integrations team's question around ensuring that we raise events once the transaction for activation and inactivations are committed to the DB. It replaces the `outboundEventsPublisher` calls to publish with its own call to `publishEvent` which then searches for the relevant process to action based on the `@TransactionalEventListener(phase = TransactionPhase.AFTER_COMMIT)` annotation.
> CVSL-1677 add application event publisher

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/ComReviewCount.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/repository/LicenceRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/privateApi/StaffController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/StaffService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/StaffIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/StaffServiceTest.kt
- src/test/resources/test_data/seed-hard-stop-licences.sql
This PR is to introduce a new endpoint to retrieve  the counts of cases that the probation practitioner needs to review for hard stop. This provides the counts for the PP's own cases and the count for the team(s) the PP is attached to as well.
> CVSL-1680 add endpoint to show review counts for PP

- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/domainEvents/OutboundEventsPublisherIntegrationTest.kt
This PR is to add in an integration test scenario to ensure we are testing that an event does actually publish to the topic successfully and that we can ping the queue to see the event on the queue.
> CVSL-1517 add integration test to test whether the event does publish to the topic

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/ToModelTransformers.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceServiceTest.kt
Without this change, HARD_STOP licences that were not approved in time for release would show in the vary tab for PPs.
> CVSL-1450 Setting isReviewNeeded to be false when a licence is not ACTIVE

- detekt-baseline.xml
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/WorkingDaysService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/WorkingDaysServiceTest.kt
This PR is to add a WorkingDaysService in the backend to aid calculation of dates when we need to calculate using working days (as needed to change the logic in the `isInHardStopPeriod` in CVSL-1724)
> CVSL-1724 add working days service as needed to calculate early release cases

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/UpdateSentenceDateService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/UpdateSentenceDateServiceTest.kt
This PR is to address a bug found in testing where incorrect licences were being timed out upon date change. An additional check to check for in progress licences has been added which mirrors how the time out job operates.
> CVSL-1828 add extra check to check that licence is in progress before timing out

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/CaseloadItem.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/CaseloadService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/ReleaseDateService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/CaseloadServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/NotifyServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/ReleaseDateServiceTest.kt
This is being recalculated on the frontend when there is no licence - this means we can remove that bit of logic
> CVSL-1829 Adding isEligibleForEarlyRelease to caseload item

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/LicenceSummary.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/ToModelTransformers.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/privateApi/LicenceControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceServiceTest.kt
This PR is to address a bug where Last Worked On By was not populated in the frontend in the CA view.
> CVSL-1832 add updatedByFullName to licence summary

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/repository/LicenceRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/privateApi/jobs/InactivateRecallLicencesController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/jobs/InactivateRecallLicencesService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/InactivateRecallLicencesIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/privateApi/jobs/InactivateRecallLicencesControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/jobs/InactivateRecallLicencesServiceTest.kt
- src/test/resources/test_data/seed-licences-for-inactivate-recall-licences.sql
This PR is to add the job to inactivate active licences and their variations where a PRRD has been entered, meaning the person has been recalled.
> CVSL-1738 add inactivate recall job to backend

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/config/ResourceServerConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/privateApi/CaseloadController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/CaseloadService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/prison/PageResponse.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/prison/PrisonerSearchApiClient.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/CaseloadIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/wiremock/PrisonerSearchMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/CaseloadServiceTest.kt
Prompt job is currently restricted as it tries to load upcoming releases across all prisons and is capped by max limit of 2000 cases. 
This will allow us to iterate across pages and gather info for everyone
> CVSL-1910 Adding new paginated endpoint

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/EligibilityService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/EligibilityServiceTest.kt
TypeScript interprets `null` as `falsy`, so `!null` is `true`.
Our existing Kotlin code does not follow this same behaviour, which appears to be causing a crash for some PP caseloads.
> CVSL-2079 Changing indeterminate sentence eligibility criteria to match previous TypeScript equivalent to fix crash

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/EligibilityService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/EligibilityServiceTest.kt
Has the same intention as https://github.com/ministryofjustice/create-and-vary-a-licence-api/pull/576
The same bug was seen with the `recall` flag, so implementing the same solution.
> CVSL-2079 Changing recall flag handling to match previous TS caseload builder

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/policies/PolicyV3.kt
Condition 4a has essentially had both a text change, and a split between the existing condition and a new condition.
We don't currently have functionality to handle a text change and split, so we instead decided it would be better to model it as a condition deletion and replacement by two new conditions.
This was approved by the policy team.
> CVSL-2151 Condition 4a refactor

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/config/OpenApiConfiguration.kt
This PR is to fix a LocalTime issue where it was being unmarshalled as a string but as an object:
```
{
"hour": 0,
"minute": 0,
"nano": 0,
"second": 0
}
```
The fix includes creating a new `Schema<LocalTime>` object, setting its type to "string", its format to "HH:mm", and providing an example value. Then I have replaced the default schema for `LocalTime` with this custom schema.
Before:
After:
> CVSL-2329 replace LocalTime schema with string

- helm_deploy/values-dev.yaml
- helm_deploy/values-test1.yaml
- helm_deploy/values-test2.yaml
This will shut down pods between 10pm - 6:30am UTC on weekdays and all day on weekends. 
6:30am was chosen as the RDS startup happens between 6am and 6:30am.
> CVSL-2399 enabling scheduled downtime

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/hdc/HdcLicenceData.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/HdcServiceTest.kt
This PR is to match the output of the HDC API now that we are returning null when curfew times are not recorded rather than a list of null fields.
> CVSL-2329 return null rather than null fields if no recorded curfew times

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/jobs/LicenceActivationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/jobs/LicenceActivationServiceTest.kt
Realised that these changes would work for newly created IS91 licences, but would potentially break existing IS91 licences.
As such the logic is being reverted (it will continue to work for new IS91 licences), and can be reimplemented after the data-fix to recalculate LSDs has been performed.
> CVSL-2269 Reverting changes affecting IS91 activation until after data fix

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/caseload/ComCaseloadService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/caseload/ComCaseloadServiceTest.kt
Ensures that the release date is correctly calculated for NOT_STARTED cases.
Also changed logic to filter out cases without NOMIS records as they wouldn't be eligible for CVL anyway, and even if one did sneak through somehow, it would blow up on `LicenceType.getLicenceType(case.nomisRecord!!)`
This could _potentially_ impact post-release cases if something happened to the PoP's NOMIS record, but that would be an error case that arguably we shouldn't account for anyway.
> CVSL-2269 Adding new LSD logic to COM caseload

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/jobs/LicenceActivationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/LicenceActivationIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/wiremock/PrisonApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/wiremock/PrisonerSearchMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/jobs/LicenceActivationServiceTest.kt
- src/test/resources/test_data/seed-licences-for-activation.sql
This PR is to change the logic in the `LicenceActivationService` to activate HDC licences when they are approved and to not deactivate HDC licences at CRD.  @SebNegahbanMoJ's work around the LSD means that for HDC licences, the LSD will be the HDCAD so now at LSD:
- The job will check the HDC status in NOMIS (as before)
- If HDC is approved and the licence being potentially activated is a HDC licence, we activate as normal (new logic)
- If HDC is approved and there is any other kind of licence, they are not made active. (as before)
- The HDC licence will not be deactivated at LSD if the HDC approval status has changed in HDC. (new logic)
> CVSL-2483 change the licence activation job to allow HDC licences

- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/UpdateSentenceDateServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/jobs/TimeOutLicencesServiceTest.kt
This PR is to add a test to confirm that HDC licences do not time out following a sentence date update which moves them into the hard stop window. The job and sentence date changes already work to not time out the HDC licences but this is just a test to cover the scenario.
> CVSL-2485 add test coverage

- detekt-baseline.xml
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/ReleaseDateService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/ReleaseDateServiceTest.kt
The past PED check has resulted in several support issues reporting that the LSD has been calculated incorrectly.
From discussing with Laura, we believe that any cases intended to be caught by this check would also have an APD, which would make them ineligible for CVL. As such, this check is redundant and is causing issues for users, so is being removed.
> CVSL-2647 Removing past PED check from new licence start date calculations

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/hdc/CurfewAddress.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/HdcIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/wiremock/HdcApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/HdcServiceTest.kt
This PR is to adjust the model which returns a curfew address from the HDC API. This is to match what will be from the HDC API for curfew addresses.
> CVSL-2596 change model to include county and adjust names of variables

- helm_deploy/create-and-vary-a-licence-api/templates/cronjob-data-extractor-analytics.yaml
We had a critical alert from dependabot in the data extractor repository which required us to bump a few dependencies and create a new release. This PR bumps the data extractor to the latest release. We've tested this with the calculate-release-dates service and it worked without issue. Hope this is ok - happy to discuss. Thanks!
> Update data extractor to latest

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/documents/Document.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/documents/DocumentApiClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/documents/DocumentType.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/ExclusionZoneIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/documents/DocumentApiClientTest.kt
Added new DocumentApiClient and uploadDocument in order to upload exclusion map documents to the external document service.
> CVSL-2862: Added Document API client and ability to upload document

- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/config/PostgresContainer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/IntegrationTestBase.kt
- src/test/resources/application-test.yml
Old time:
`SUCCESS: Executed 225 tests in 3m 4s (1 skipped)`
New Time:
`SUCCESS: Executed 225 tests in 2m 22s (1 skipped)`
> CVSL-3048 Improved integration db connection times

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/documents/DocumentApiClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/documents/DocumentService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/documents/DocumentApiClientDownloadTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/documents/DocumentApiClientUploadTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/documents/DocumentServiceDownloadDocumentTest.kt
Added API client and service method for downloading document files.
Not currently plumbed in to anything.
Removed some excessive repetition of the uuid in one of the tests.
> CVSL-3022: Api client and service layer for document downloads

- src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/caseload/ComCreateCaseloadService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/caseload/ComCreateCaseloadServiceTest.kt
licenceId is null when the case is `NOT_STARTED`, as the "licence" being referenced is a pre-creation placeholder.
> CVSL-3137 Making NOT_STARTED hard stop cases redirect to PRISON_WILL_CREATE_THIS_LICENCE
