Dockerfile
=> CVL-14: Install root cert for Postgresql into Dockerfile

src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/Licence.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/LicenceController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/util/LicenceStatus.kt, src/main/resources/migration/common/V14__add_recall_and_alter_superseded.sql
Added RECALLED status to API.
Renamed SUPERSEDED to INACTIVE.
=> CVSL-127: Added new status of RECALLED. Renamed SUPERSEDED to INACTIVE.

src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/ContactNumberRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/LicenceController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/LicenceIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/LicenceControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceServiceTest.kt
API changes to accept updated contact number for the officer on a licence.
=> CVSL-102: Update the contact telephone number for a licence

src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/Licence.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/LicenceSummary.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/repository/LicenceRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/LicenceController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/TransformFunctions.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/util/LicenceStatus.kt, src/main/resources/migration/common/V12__load_licence_status_values.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/LicenceIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/LicenceControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceServiceTest.kt, src/test/resources/test_data/seed-licence-summaries.sql
- Add Approved licence status
- Add endpoint for searching licences associated to a supervising probation officer by status
=> CVSL-134: Find licence summaries by staff id and status

helm_deploy/create-and-vary-a-licence-api/Chart.yaml, helm_deploy/values-dev.yaml
* This should deploy to the new cluster (live)
=> CVSL-229: Update generic-service version and switch ingress to live (context green)

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/entity/AdditionalConditionUploadDetail.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/entity/AdditionalConditionUploadSummary.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/AdditionalConditionUploadSummary.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/ExclusionZoneService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/TransformFunctions.kt
Tidy-up after more local testing.
=> CVSL-255: Converted thumbnail to base64 and adjusted @Lob columns to @Basic.

src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/ExclusionZoneService.kt
This produces a larger, clearer image of the exclusion zone map by extracting the image instead of rendering an image of page 1 (with borders/text).
=> CVSL-304: Extract full size image in place of a snapshot of page 1.

build.gradle.kts, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/health/InfoTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/ExclusionZoneControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/LicenceControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/TestDataControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/ExclusionZoneServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceServiceTest.kt
No functional changes - dependencies and import changes only.
=> CVSL-315: Update dps-gradle-springboot plugin to latest version + dependency updates

build.gradle.kts
Fix vulnerability in Tomcat reported overnight.
=> CVSL-384: Update gradle plugin

build.gradle.kts
To fix Trivy scan issue overnight
=> CVSL-388: Update postgresql dependency

src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/entity/Licence.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/Licence.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/request/ReferVariationRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/repository/LicenceSpecifications.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/LicenceController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/TransformFunctions.kt, src/main/resources/migration/common/V11__create_licence_tables.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/LicenceControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceServiceTest.kt
* Adds an endpoint to approve a variation
* Adds an endpoint to refer a variation
* Adds PDU to the list of licence matching criteria
* Unit tests to cover the above
(Integration tests to follow)
=> CVSL-394:  Variation approval and rejection/referral endpoints

.circleci/config.yml, helm_deploy/values-prod.yaml
* CircleCI pipeline to push to production.
* `values-prod.yaml` configuration.
=> CVSL-377 prod helm API values

helm_deploy/create-and-vary-a-licence-api/Chart.yaml
Updated generic-service from 1.1.2  to 1.2.2
Updated generic-prometheus-alerts from 0.2.7 to 0.3.0
=> CVSL-369: Updating to latest versions of helm charts

src/main/resources/migration/common/V15__update_column_size.sql
Erring on the side of caution....
=> CVSL-429: Update licence column lengths

helm_deploy/create-and-vary-a-licence-api/values.yaml
Request from Chris Pugh, after discussions with Laura.
=> CVSL-470: Allow IP source access to approved-premises-team for swagger docs

src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/entity/AdditionalCondition.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/AdditionalCondition.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/UpdateAdditionalConditionDataRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/TransformFunctions.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/LicenceIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/LicenceControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceServiceTest.kt
This reverts commit 74f0708cf29c5b44afc7a127c243d83cfdf91c02.
=> CVSL-359: Reinstate storing expanded additional conditions

build.gradle.kts
Should resolve overnight checks.
=> CVSL-509: Update gradle spring plugin

build.gradle.kts
Fix or suppress overnight warnings.
=> CVSL-522: Updated gradle plugin.

src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceServiceTest.kt
The trigger for setting the old licence to INACTIVE has been moved to the `Activate licence` button in the UI service.
In addition to setting the variation ACTIVE it will now call updateLicenceStatus to set the varied licence to INACTIVE too.
=> CVSL-556: Avoid setting varied licence to INACTIVE when new one is approved

src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/NotifyService.kt, src/main/resources/application.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/NotifyServiceTest.kt
Send email to OMU if an approved licence is changed to IN_PROGRESS
=> Cvsl 411 notify omu

src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/entity/Licence.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/LicenceSummary.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/repository/LicenceSpecifications.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/TransformFunctions.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/LicenceControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceServiceTest.kt, src/test/resources/test_data/seed-matching-candidates.sql
Include the licence date created value for licence summary
=> Cvsl 446 pduh region view

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/config/ResourceServerConfiguration.kt
Upgrade to HMPPS Spring 4.1.1. Target JVM 18 in line with upgrade to Docker image. Update deprecated WebSecurityConfigurerAdapter to SecurityFilterChain Bean.
=> Upgrade spring 4 4 1

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/config/WebClientConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/LicenceStatistics.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/functions.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/LicenceStatisticsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceStatisticsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/prison/Prison.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/prison/PrisonRegisterApiClient.kt, src/main/resources/application-dev.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/LicenceStatisticsControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceStatisticsServiceTest.kt, src/test/resources/application-test.yml
Draft request as require tests
=> CVSL-442 initial commit for metrics needed by support team

src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/policy/AdditionalConditionAp.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/policy/AdditionalConditionPss.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/policy/ConditionalInput.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/policy/Input.kt, src/main/resources/policy_conditions/policyV2.1.json, src/main/resources/policy_conditions/policyV2.json
Also minor changes to model definitions.
=> CVSL-138 Policy Version 2.1 changes, and adding types to Policy V2.0

helm_deploy/create-and-vary-a-licence-api/values.yaml
The process will be enable the second ingress deploy to prod and then remove the old ingress and push out to prod
=> CVSL-668 Enabling new ingress

src/main/resources/policy_conditions/policyV2.1.json
Changing the behaviour of condition 4a to match expectation of users
=> Re-adding the ability to select options for condition 4a, but without the course centre input

.circleci/config.yml, helm_deploy/values-test1.yaml
if you push to the test1 branch it will deploy the api server to the `create-and-vary-a-licence-test1` namespace
and be available here:
https://create-and-vary-a-licence-api-test1.hmpps.service.justice.gov.uk/info
=> Adding test deployment

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/config/WebClientConfiguration.kt, src/main/resources/application-dev.yml, src/test/resources/application-test.yml
This PR is to add both community API and probation search clients to the API to allow us to call endpoints on the community API and probation search from the backend.
=> CVSL-1030 Add in community api client and probation search client in api

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, helm_deploy/values-test1.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/config/WebClientConfiguration.kt
was expecting no underscore if variable name
=> Fix env var name

.circleci/config.yml
Potentially fix app version disappearing during deployment
=> Upgrading orb version, hoping to fix intermittent deployment issue 

src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/ProbationSearchResult.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/TransformFunctions.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/probation/Manager.kt, src/main/resources/application-dev.yml
PR including some changes to the data model based on some of the data coming back from the mock.
=> CVSL-1030 changes based on data returned from mock

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/config/WebClientConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/prison/PrisonerSearchApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/prison/PrisonerSearchPrisoner.kt, src/main/resources/application-dev.yml, src/test/resources/application-test.yml
Also adding the `searchByNomisIdsEndpoint` in advance of using it in a later PR for CVSL-1023
=> Adding prisoner search API client

src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/jobs/LicenceActivationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/jobs/LicenceActivationServiceTest.kt
Now creates an audit log when an offender cannot be found, rather than breaking the job entirely.
=> Fixing job crashing due to missing offender in PrisonerSearchAPI

README.md, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/AuditController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/ComController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/EventController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/ExclusionZoneController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/LicenceActivationController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/LicenceController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/LicenceOverrideController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/LicencePolicyController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/LicenceStatisticsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/OffenderController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/OmuContactController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/Tags.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/UnapprovedLicenceController.kt
**BEFORE**:
<kbd>
</kbd>
**AFTER**:
<kbd>
</kbd>
=> CVSL-1131 Improving API docs

src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceConditionService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/ToEntityTransformers.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/ToModelTransformers.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceConditionServiceTest.kt
Also split out toEntity and toModel transformers
=> CVSL-1127 Only compare formatting when additional data is provided

src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/request/UpdateOffenderDetailsRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/OffenderController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/OffenderService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/OffenderControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/OffenderServiceTest.kt
Paired with UI PR [here](https://github.com/ministryofjustice/create-and-vary-a-licence/pull/575)
=> Adding endpoint to update offender name and DOB

src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/config/ClientTrackingConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/AuditController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/ComController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/LicenceController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/OffenderController.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/ControllerTest.kt
Added a test to catch this happening in the future
Also adding the standard client tracking configuration code so we can determine who is calling our service for when we have future clients
=> CVSL-1229 Adding missing Valid annotations to enforce rules

build.gradle.kts
This PR is to bump assert4j and Detekt plugins.
=> CVSL-1241 update assert4j and detekt plugins

src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/AuditService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceConditionService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/jobs/RemoveApConditionsInPssPeriodService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/AuditServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceConditionServiceTest.kt
Also preventing updates when no changes taking place
=> CVSL-465 Adding logging

src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/IS91DeterminationService.kt
Tested locally by running existing specs that called the affected method, and the output was as expected.
=> CVSL-1298 Adding logging to licence activation job to show offence histories

detekt-baseline.xml, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/BankHolidayController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/gov/GovUkApiClient.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/BankHolidaysIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/BankHolidayControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/BankHolidayServiceTest.kt
Reverts ministryofjustice/create-and-vary-a-licence-api#323
=> Revert "CVSL-1250 send the bank holiday object instead of list of dates"

src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/AdditionalConditionData.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/policy/Input.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/privateApi/LicenceControllerTest.kt
This bit of metadata determines whether a user should be shown a field or not
=> CVSL-1163 Adding derived 'contributesToLicence' field

.circleci/config.yml, helm_deploy/values-test2.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/AdditionalCondition.kt
Always deploy test2 on deploy to main
Also making condition code a required field to fix typing in ui
=> Pointing test2 to real delius

detekt-baseline.xml, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/publicApi/PublicLicencePolicyController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/publicApi/model/licencePolicy/ConditionTypes.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/publicApi/model/licencePolicy/LicencePolicyAdditionalCondition.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/publicApi/model/licencePolicy/LicencePolicyConditions.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/publicApi/PublicLicencePolicyService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/publicApi/ToModelTransformers.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/publicApi/PublicLicencePolicyServiceIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/publicApi/PublicLicencePolicyControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/publicApi/PublicLicencePolicyServiceTest.kt, src/test/resources/test_data/publicApi/licencePolicy/policyV1.json, src/test/resources/test_data/publicApi/licencePolicy/policyV2.json, src/test/resources/test_data/publicApi/licencePolicy/policyV2_1.json
This PR is to add a new endpoint to the CVL public API to allow a policy representations to be returned based on the version of the policy that is required.
=> CVSL-1282 add endpoint to retrieve policy by version number

src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/PrisonerForRelease.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/NotifyService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/UpdateSentenceDateService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/NotifyServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/UpdateSentenceDateServiceTest.kt
Reverts ministryofjustice/create-and-vary-a-licence-api#356
=> Revert "CVSL-1435-Email-add-date-to-changes-made-email"

src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/PrisonerForRelease.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/NotifyService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/UpdateSentenceDateService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/NotifyServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/UpdateSentenceDateServiceTest.kt
Reverts ministryofjustice/create-and-vary-a-licence-api#358
=> Revert "Revert "CVSL-1435-Email-add-date-to-changes-made-email""

src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/policies/PolicyV2Dot1.kt, src/test/resources/test_data/policy_conditions/policyV2_1.json, src/test/resources/test_data/publicApi/licencePolicy/policyV2_1.json
Reverts ministryofjustice/create-and-vary-a-licence-api#363
=> Revert "CVSL-1352-New condition Anonymous victim condition to be added to CVL"

.trivyignore, build.gradle.kts
Reverts ministryofjustice/create-and-vary-a-licence-api#379
Flyway error - seemed to be stopping migrations from happening - reverting pending investigation
=> Revert "CVSL-1496 update gradle dependencies"

.trivyignore, build.gradle.kts
Reverts ministryofjustice/create-and-vary-a-licence-api#385
=> Revert "Revert "CVSL-1496 update gradle dependencies""

helm_deploy/create-and-vary-a-licence-api/Chart.yaml, helm_deploy/create-and-vary-a-licence-api/templates/cronjob-data-extractor-analytics.yaml, helm_deploy/create-and-vary-a-licence-api/values.yaml, helm_deploy/values-dev.yaml, helm_deploy/values-prod.yaml
Reverts ministryofjustice/create-and-vary-a-licence-api#389
=> Revert "CVSL-1526 Moving data extractor to helm chart"

helm_deploy/create-and-vary-a-licence-api/templates/cronjob-data-extractor-analytics.yaml
Based on what another project has done
=> CVSL-1583 exclude additional condition data temporarily

helm_deploy/create-and-vary-a-licence-api/values.yaml
This PR is to introduce the HMPPS_SQS_USE_WEB_TOKEN to our helm deploy as we are now using IRSA.
=> CVSL-1516 add env var to values.yaml

.circleci/config.yml, README.md, async-api.yml, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/domainEvents/OutboundEventsPublisher.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/IntegrationTestBase.kt
This PR is to add event documentation, now that we are raising events to the `hmpps-domain-topic`.
=> CVSL-1518 add async spec

.circleci/config.yml, helm_deploy/values-dev.yaml, helm_deploy/values-test1.yaml
Always deploy HEAD of main to test1 and disable test1 branch deploy
=> Moving to use hard stop in test1

helm_deploy/values-preprod.yaml
This PR is to enable hard stop in preprod to allow for some extra testing.
=> CVSL-1808 enable hard stop in preprod

src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/UpdateSentenceDateService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/caseload/ApproverCaseloadService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/probation/CommunityApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/probation/OtherIds.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/probation/ProbationAreaDetail.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/probation/ProbationSearchApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/probation/StaffDetails.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/caseload/ApproverCaseloadServiceTest.kt
This PR is to add some extra calls to the clients in preparation of moving the approver caseload to the backend.
=> CVSL-1906 add calls to probation search and community api

src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/probation/User.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceCreationServiceTest.kt
Missed a field from my previous PR.
=> CVSL-1906 add missing field needed for approvals

src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/ProbationPractitioner.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/caseload/ApproverCaseloadService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/caseload/ApproverCaseloadServiceTest.kt
This PR is to introduce the approver caseload service to the backend. This includes porting the service that is currently in the frontend to the backend.
=> CVSL-1906 add approver caseload service to back end

src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/EligibilityService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceFactory.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/PrisonerSearchService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/caseload/ApproverCaseloadService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/prison/PrisonerSearchFunctions.kt
This is a separate PR to address the feedback comments left in the previous [PR](https://github.com/ministryofjustice/create-and-vary-a-licence-api/pull/545).
=> CVSL-1906 address PR comments

src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/caseload/ApproverCaseloadService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/caseload/ApproverCaseloadServiceTest.kt
This PR adds further test coverage for the approver caseload.
=> CVSL-1906 add further unit tests to cover scenarios in approver caseload

src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/caseload/ApproverCaseloadService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/caseload/ApproverCaseloadServiceTest.kt
This PR is to add the functionality to retrieve the recently approved caseload.
=> CVSL-1906 add recently approved caseload

src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/privateApi/CaseloadController.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/privateApi/CaseloadControllerTest.kt
This PR is to add the last remaining endpoint for the approver caseload to get recently approved cases.
=> CVSL-1906 add recently approved endpoint

src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/privateApi/LicenceController.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/LicenceIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/privateApi/LicenceControllerTest.kt
This PR is the backend change to remove the two old endpoints used for the approver caseload.
=> CVSL-1906 remove old endpoints and tests

src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/policies/PolicyV3.kt, src/test/resources/test_data/policy_conditions/policyV3.json
Also brings json representation up-to-date
=> CVSL-2238 Policy content tweaks from UCD review

src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/policies/PolicyV3.kt, src/test/resources/test_data/policy_conditions/policyV3.json
QA review spotted some changes to condition content that was missed.
=> CVSL-2238 Adding missed tweaks to policy condition wording

src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/LicenceSummary.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/ToModelTransformers.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/caseload/CaCaseloadService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/caseload/CaCaseloadServiceTest.kt
This PR adds some missing logic to set the HDCAD if it is available for the CA probation caseload.
=> CVSL-2337 add missing HDCAD label for CA probation view cases

src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/caseload/ComCaseloadService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/jobs/NotifyAttentionNeededLicencesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/prison/PrisonApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/prison/PrisonerSearchApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/probation/DeliusApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/probation/ProbationSearchApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/util/Batching.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/caseload/ComCaseloadServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/util/BatchingTest.kt
We apply batching inconsistently and at different levels- this moves batching down and applies it consistently.
=> CVSL-2478 consistently batch calls at the api layer

helm_deploy/create-and-vary-a-licence-api/values.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/repository/LicenceRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/privateApi/jobs/DeactivateHdcLicencesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/jobs/DeactivateHdcLicencesService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/DeactivateHdcLicencesIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/privateApi/jobs/DeactivateHdcLicencesControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/jobs/DeactivateHdcLicencesServiceTest.kt, src/test/resources/test_data/seed-licences-for-deactivate-hdc-licences-past-release-date.sql
This PR is to add a new job which will deactivate HDC licences at CRD - 9 days.
=> CVSL-2505 add new job to deactivate HDC licences past their release date

src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/config/ResourceServerConfiguration.kt
Job keeps failing as it times out as async is not enabled
=> CVSL-2478 Enabling async

helm_deploy/create-and-vary-a-licence-api/values.yaml, helm_deploy/values-dev.yaml, helm_deploy/values-test1.yaml, helm_deploy/values-test2.yaml
Also moving dev jobs into office hours
=> CVSL-2571 don't retry jobs sending emails

detekt-baseline.xml, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/config/ControllerAdvice.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/resource/privateApi/AddressSearchResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/addressSearch/AddressSearchService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/addressSearch/OsPlacesApiClient.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/AddressSearchResourceIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/wiremock/OsPlacesMockServer.kt
=> CVSL-2882 Server side - address search results pagination

src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/publicApi/PublicLicenceService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/publicApi/PublicLicenceServiceTest.kt
I have found another place where the fullSizeImage field was being called directly and updated to use the document service logic.
=> CVSL:2862: PublicLicenceService updated to pull images from correct location

src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceServiceTest.kt
Audit looks okay! and other emails!
=> CVSL-3091 Check the comName variable in emails

run-local.sh, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/conditions/ExclusionZoneService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/ExclusionZoneIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/LicenceConditionIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/documents/ExclusionZoneServiceDeleteDocumentsIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/integration/wiremock/DocumentApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/LicenceServiceTest.kt
Also adding mechanism to debug when running from spring boot
=> CVSL-3153 Fix documentation deletion

src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/caseload/CaCaseloadService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/documents/DocumentApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/hdc/HdcApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/prison/PrisonApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/prison/PrisonerSearchApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/probation/DeliusApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/probation/WorkLoadApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/util/ResponseUtils.kt
Also little bit of tidy up of CA caseload
=> CVSL-3153 Tidying up response handling

src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/model/CaCase.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/caseload/CaCaseloadService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/createandvaryalicenceapi/service/caseload/CaCaseloadServiceTest.kt
Reverts ministryofjustice/create-and-vary-a-licence-api#946
=> Revert "CVSL-3311 Fix release date kind"
